# Generated by Django 5.0.6 on 2024-07-22 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='type',
        ),
    ]
