# Generated by Django 5.0.6 on 2024-08-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_remove_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='createdDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
