# Generated by Django 5.0.6 on 2024-08-06 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        ('message', '0004_message_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('one', 'One Time'), ('many', 'Many Times')], default='1', max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='event',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
    ]
