# Generated by Django 5.0.6 on 2024-08-06 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        ('message', '0005_message_type_alter_message_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
    ]
