# Generated by Django 5.0.6 on 2024-08-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_alter_message_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('one', 'One Time'), ('many', 'Many Times')], default='one', max_length=255),
        ),
    ]
