# Generated by Django 5.0.6 on 2024-07-10 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('seat_no', models.CharField(max_length=255)),
                ('gender', models.BooleanField()),
                ('profile', models.TextField(default=None)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('face', models.BooleanField()),
                ('facial_feature', models.TextField(default=None)),
                ('memo', models.TextField()),
                ('status', models.PositiveSmallIntegerField()),
                ('role', models.PositiveSmallIntegerField()),
                ('phone_1', models.CharField(max_length=30)),
                ('phone_2', models.CharField(default=None, max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
    ]
