# Generated by Django 5.0.6 on 2024-07-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='facial_feature',
            field=models.TextField(default=None),
        ),
    ]
