# Generated by Django 5.0.6 on 2024-07-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='facial_feature',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_2',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='profile',
            field=models.TextField(default=None, null=True),
        ),
    ]
