# Generated by Django 5.0.6 on 2024-07-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_alter_participant_facial_feature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='face',
            field=models.BooleanField(default=False),
        ),
    ]
