# Generated by Django 5.0.6 on 2024-07-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_alter_participant_facial_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='profile',
            field=models.TextField(default=None),
        ),
    ]
