# Generated by Django 5.0.6 on 2024-07-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0003_alter_participant_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='memo',
            field=models.TextField(default=None, null=True),
        ),
    ]
