# Generated by Django 5.0.6 on 2024-07-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0004_alter_participant_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
