# Generated by Django 5.0.6 on 2024-07-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0005_alter_participant_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='face',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='facial_feature',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='status',
        ),
        migrations.AlterField(
            model_name='participant',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='participant',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='profile',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='participant',
            name='seat_no',
            field=models.CharField(max_length=50),
        ),
    ]
