# Generated by Django 5.0.6 on 2024-07-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0006_remove_participant_face_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='face',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='facial_feature',
            field=models.TextField(default=None, null=True),
        ),
    ]
