# Generated by Django 5.0.6 on 2024-08-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0007_participant_face_participant_facial_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='facial_feature',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
