# Generated by Django 5.0.6 on 2024-07-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_1', models.TimeField()),
                ('leave_1', models.TimeField()),
                ('entry_2', models.TimeField()),
                ('leave_2', models.TimeField()),
                ('date', models.DateField()),
                ('cmd', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
