# Generated by Django 5.0.6 on 2024-08-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_entry_1_alter_attendance_entry_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='entry_1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='entry_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='leave_1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='leave_2',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
