# Generated by Django 5.0.6 on 2024-08-07 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_entry_1_alter_attendance_entry_2_and_more'),
        ('participant', '0008_alter_participant_facial_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='entry_1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='entry_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='leave_1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='leave_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='participant.participant'),
        ),
    ]
